const diTich = [
  {
    id: 1,
    ten: "Đình làng Túy Loan",
    loai: "Di tích kiến trúc nghệ thuật cấp quốc gia",
    diaChi: "Thôn Túy Loan Đông, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.99782615342037,
    lng: 108.13694307218168,
    xepHang: "Di tích Kiến trúc Nghệ thuật cấp Quốc gia (Được công nhận năm 1999)",
    moTa: "Đình làng Túy Loan là một công trình kiến trúc cổ kính, tinh xảo nằm bên bờ một nhánh sông Túy Loan thơ mộng. Đình có khuôn viên rộng lớn lên đến 8008 m2, được xây dựng theo bố cục 3 gian 2 chái truyền thống với mái lợp ngói âm dương và tường gạch dày 30cm. Mặt tiền đình nổi bật với bức bình phong cuốn thư cao 3m đắp nổi hình long mã và các linh vật bằng sành sứ công phu do bàn tay tài hoa của thợ mộc Kim Bồng (Hội An) thực hiện.",
    lichSu: "Đình được khởi dựng vào khoảng cuối thế kỷ 15 bằng tranh tre nứa lá bởi các vị tiền hiền của 5 dòng họ lớn (Đặng, Lâm, Nguyễn, Trần, Lê) có công khai khẩn lập ấp. Trải qua hơn 5 thế kỷ, đình từng bị cháy rụi và được xây dựng lại vào năm 1888 (Mậu Tý), rồi tiếp tục dựng lại sau trận bão năm 1900. Trong kháng chiến, nơi đây là địa bàn cách mạng quan trọng: điểm tập trung giành chính quyền tháng 8/1945, trạm cứu thương của Tieu đoàn 17 năm 1947, và từng bị địch chiếm làm trung tâm huấn chính gắt gao giai đoạn 1955-1957. Đình hiện còn lưu giữ 20 sắc phong thần của các vua triều Nguyễn.",
    hinhAnh: "images/tuyloan.jpg",
    googleMaps: "https://www.google.com/maps?q=15.99782615342037,108.13694307218168",
    video: "https://www.youtube.com/embed/p9I2p_b7G_Y?origin=https://hieuvhc-create.github.io",
    taiLieu: ""
  },
  {
    id: 2,
    ten: "Đình làng Bồ Bản",
    loai: "Di tích lịch sử - văn hóa",
    diaChi: "Thôn Bồ Bản, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.987953179337236,
    lng: 108.1518397085302,
    xepHang: "Di tích Kiến trúc Nghệ thuật cấp Quốc gia (Được công nhận năm 1999)",
    moTa: "Đình làng Bồ Bản là một trong những ngôi đình cổ hiếm hoi còn giữ được vẻ đẹp nguyên vẹn tại Đà Nẵng. Đình được xây dựng theo lối kiến trúc 3 gian 2 chái, lợp mái ngói âm dương truyền thống. Không gian nội thất bên trong được chạm khắc hết sức tinh xảo bởi bàn tay tài hoa của các nghệ nhân mộc Kim Bồng (Hội An), thể hiện qua các hoa văn tứ quý, mây uốn, đầu rồng đuôi lá độc đáo. Mặt trước đình có sân rộng và bức bình phong cuốn thư ghép mảnh sành sứ hình mãnh hổ uy nghi.",
    lichSu: "Làng Bồ Bản được khai khẩn từ cuối thế kỷ 15 (khoảng năm 1476). Ngôi đình bàn đầu dựng bằng tranh tre vào năm 1800, sau đó được dịch chuyển và xây kiên cố vào năm 1852. Trải qua nhiều biến động, đình được đại trùng tu vào các năm 1906 và 1990 nhưng vẫn giữ đúng các yếu tố gốc ban đầu. Nơi đây ghi dấu nhiều sự kiện cách mạng quan trọng: điểm tập hợp cướp chính quyền tháng 8/1945, địa điểm lập phòng phiếu bầu cử Quốc hội đầu tiên và là nơi xét xử tề ngụy, tiếp nhận ngụy quân đầu thú sau giải phóng.",
    hinhAnh: "images/boban.jpg",
    googleMaps: "https://www.google.com/maps?q=15.987953179337236,108.1518397085302",
    video: "https://www.youtube.com/embed/-TKEsrumxuc"
  },
  {
    id: 3,
    ten: "Miếu Ông Ích Đường",
    loai: "Di tích lịch sử - văn hóa",
    diaChi: "Thôn Hòa Phong, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.992397705238226,
    lng: 108.1423274817334,
    xepHang: "Di tích Lịch sử – Văn hóa",
    moTa: "Miếu thờ danh tướng Ông Ích Đường, một nghĩa sĩ yêu nước kiên trung trong phong trào chống Pháp đầu thế kỷ 20.",
    lichSu: "Miếu được lập nên nhằm tưởng nhớ và tri ân tấm lòng vì nước vong thân của Ông Ích Đường, giáo dục truyền thống yêu nước cho thế hệ mai sau.",
    hinhAnh: "images/ongichduong.gif",
    googleMaps: "https://www.google.com/maps?q=15.992397705238226,108.1423274817334",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 4,
    ten: "Khu Căn cứ Huyện ủy Hòa Vang",
    loai: "Di tích lịch sử",
    diaChi: "Thôn Phú Túc, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.964949682778094,
    lng: 108.05078200152602,
    xepHang: "Di tích Lịch sử Cách mạng",
    moTa: "Khu căn cứ cách mạng bí mật nằm địa hình rừng núi hiểm trở, đóng vai trò đầu não lãnh đạo quân và dân Hòa Vang.",
    lichSu: "Nơi đây từng là nơi đóng quân, hội họp và đưa ra những quyết sách, chỉ đạo quan trọng của Huyện ủy Hòa Vang trong suốt những năm tháng kháng chiến trường kỳ.",
    hinhAnh: "images/cancu.jpg",
    googleMaps: "https://www.google.com/maps?q=15.964949682778094,108.05078200152602",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 5,
    ten: "Đình Dương Lâm",
    loai: "Di tích lịch sử - văn hóa",
    diaChi: "Thôn Dương Lâm, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.992212986728015,
    lng: 108.12671333158963,
    xepHang: "Di tích Kiến trúc Nghệ thuật",
    moTa: "Ngôi đình mang nét kiến trúc chạm khắc rường cột tinh xảo, thể hiện rõ nếp sống tâm linh trân quý truyền thống của dân làng Dương Lâm.",
    lichSu: "Trải qua bao thăng trầm, đình vẫn lưu giữ nguyên vẹn các giá trị bài vị thờ cúng và là nơi tụ họp sinh hoạt văn hóa làng xã vào mỗi dịp lễ Tết.",
    hinhAnh: "images/duonglam.gif",
    googleMaps: "https://www.google.com/maps?q=15.992212986728015,108.12671333158963",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 6,
    ten: "Đình Cẩm Toại",
    loai: "Di tích lịch sử - văn hóa",
    diaChi: "Thôn Cẩm Toại Trung,Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.982799405738001,
    lng: 108.13882985113406,
    xepHang: "Di tích Lịch sử – Văn hóa",
    moTa: "Đình Cẩm Toại tọa lạc trên vùng đất bằng phẳng, sở hữu không gian yên bình và nét kiến trúc mái ngói rêu phong cổ kính.",
    lichSu: "Đình gắn liền với công lao khai phá của các bậc tiền nhân và giữ vai trò trung tâm trong đời sống tinh thần của cộng đồng cư dân Cẩm Toại.",
    hinhAnh: "images/camtoai.jpg",
    googleMaps: "https://www.google.com/maps?q=15.982799405738001,108.13882985113406",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 7,
    ten: "Mộ Thống chế Lê Văn Hoan",
    loai: "Di tích lịch sử",
    diaChi: "Thôn Cẩm Toại Tây, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.979213835550407,
    lng: 108.12798664297617,
    xepHang: "Di tích Lịch sử",
    moTa: "Khu mộ uy nghiêm của vị Thống chế triều đình cũ, người có đóng góp to lớn đối với an ninh và sự bình yên của vùng đất này.",
    lichSu: "Mộ phần được bảo tồn chu đáo qua nhiều thế hệ như một biểu tượng thiêng liêng thể hiện đạo lý 'Uống nước nhớ nguồn' của người dân xứ Quảng.",
    hinhAnh: "images/levanhoan.jpg",
    googleMaps: "https://www.google.com/maps?q=15.979213835550407,108.12798664297617",
    video: "https://www.youtube.com/watch?v=3FOVhWDCcf8"
  },
  {
    id: 8,
    ten: "Mộ Bình hương xử sĩ Mạc Trường Thành",
    loai: "Di tích lịch sử",
    diaChi: "Thôn Hòa Phú,Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.997279613480659,
    lng: 108.07764466873532,
    xepHang: "Di tích Lịch sử",
    moTa: "Nơi an nghỉ của bậc danh sĩ Mạc Trường Thành, một người đức độ, học rộng tài cao, giữ trọn khí tiết vẹn toàn cả đời.",
    lichSu: "Khu mộ ghi dấu cuộc đời thanh bạch và ý chí kiên trung của một vị xử sĩ yêu nước, được lưu danh trong sử sách địa phương.",
    hinhAnh: "images/mactruongthanh.webp",
    googleMaps: "https://www.google.com/maps?q=15.997279613480659,108.07764466873532",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 9,
    ten: "Trường Tiểu học An Phước",
    loai: "Di tích lịch sử",
    diaChi: "Thôn Cẩm Toại Trung,Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.983429561203332,
    lng: 108.13889179914489,
    xepHang: "Di tích Lịch sử Cách mạng",
    moTa: "Địa điểm trường học cũ, từng là cái nôi nhen nhóm và nuôi dưỡng phong trào giáo dục cũng như tinh thần yêu nước từ thời tiền khởi nghĩa.",
    lichSu: "In kháng chiến, trường vừa là nơi dạy học, vừa là cơ sở liên lạc bí mật và che giấu các chiến sĩ hoạt động cách mạng nội đô.",
    hinhAnh: "images/anphuoc.jpg",
    googleMaps: "https://www.google.com/maps?q=15.983429561203332,108.13889179914489",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 10,
    ten: "Địa điểm chiến tích Trung đoàn pháo binh 575",
    loai: "Di tích lịch sử",
    diaChi: "Thôn Cẩm Toại Trung, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.982557606437979,
    lng: 108.13203497057431,
    xepHang: "Di tích Lịch sử Chiến thắng",
    moTa: "Khu di tích đánh dấu những chiến công oanh liệt, vang dội của Trung đoàn pháo binh 575 anh hùng trên mặt trận Quảng Đà.",
    lichSu: "Nơi đây ghi dấu những trận pháo kích chuẩn xác, bẻ gãy nhiều đợt càn quét nguy hiểm của quân địch, góp phần giải phóng quê hương.",
    hinhAnh: "images/575.jpg",
    googleMaps: "https://www.google.com/maps?q=15.982557606437979,108.13203497057431",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 11,
    ten: "Đình làng Hội Vực",
    loai: "Di tích lịch sử - văn hóa",
    diaChi: "Thôn Hòa Phú, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.999193236389113,
    lng: 108.07490778247278,
    xepHang: "Di tích Lịch sử – Văn hóa",
    moTa: "Ngôi đình làng cổ kính nằm nép mình bên xóm thôn bình dị, lưu giữ vẹn nguyên nét kiến trúc rường gỗ mộc mạc xa xưa.",
    lichSu: "Đình Hội Vực là nơi tụ họp quen thuộc của bà con lối xóm trong các ngày hội làng, lễ cầu an và giữ gìn các hương ước quý báu.",
    hinhAnh: "images/hoivuc.jpg",
    googleMaps: "https://www.google.com/maps?q=15.999193236389113,108.07490778247278",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  },
  {
    id: 12,
    ten: "Bia Chiến tích Trung đội nữ Lê Thị Hồng Gấm",
    loai: "Di tích lịch sử - cách mạng",
    diaChi: "Thôn Dương Lâm, Xã Hòa Phong, Huyện Hòa Vang, TP. Đà Nẵng",
    lat: 15.992451, 
    lng: 108.139524, 
    xepHang: "Địa chỉ đỏ Giáo dục truyền thống cách mạng Huyện Hòa Vang",
    moTa: "Bia Chiến tích Trung đội nữ Lê Thị Hồng Gấm là công trình văn hóa - lịch sử ý nghĩa, được xây dựng lần đầu vào năm 2018 và mở rộng lên 500m2 vào năm 2024 nhằm tri ân sự hy sinh anh dũng của tổ chiến đấu Nguyễn Thị Xuân Mai. Điểm nhấn đặc biệt tại khuôn viên di tích là tảng đá cẩm thạch nguyên khối khắc bức thư ra trận đầy xúc động dài 388 chữ của liệt sĩ Xuân Mai gửi lại đồng đội ngay trước đêm chiến đấu. Nơi đây hiện là 'Địa chỉ đỏ' nổi bật, được bao quanh bởi các công trình cây xanh lưu niệm và đường hoa tri ân rực rỡ.",
    lichSu: "Ngày 28/01/1973 (ngay khi Hiệp định Paris có hiệu lực), quân địch xua lực lượng lớn lấn chiếm vùng giải phóng tại thôn An Tân và Dương Lâm. Tổ chiến đấu gồm Trung đội trưởng Nguyễn Thị Xuân Mai cùng các chiến sĩ Hồ Thị Hồng Vân, Ông Thị Minh Nguyệt và Lê Quốc Tuấn đã kiên cường bám trụ, cố thủ trong căn hầm nhà dân để đẩy lùi hàng chục đợt phản kích và tiêu diệt gần một đại đội địch. Dù hết đạn và bị bao vây, các chiến sĩ đã anh dũng chiến đấu đến hơi thở cuối cùng. Chiến công xuất sắc của trung đội đã góp phần giúp Đại đội 2 Khu II Hòa Vang vinh dự được phong tặng danh hiệu Anh hùng Lực lượng vũ trang nhân dân.",
    hinhAnh: "images/lethihonggam.jpg",
    googleMaps: "https://maps.google.com/?q=Bia+Chiến+tích+Trung+đội+nữ+Lê+Thị+Hồng+Gấm",
    video: "https://www.youtube.com/embed/p9I2p_b7G_Y"
  },
  {
    id: 13,
    ten: "Bến Suối Túy Loan",
    loai: "Di tích lịch sử",
    diaChi: "thôn Túy Loan Đông, Xã Hòa Vang, TP. Đà Nẵng",
    lat: 15.996116958933936,
    lng: 108.14091191375506,
    xepHang: "Di tích Lịch sử Cách mạng",
    moTa: "Bến suối thanh bình xưa kia từng là tuyến đường giao thông thủy huyết mạch đón đưa các cán bộ và vận chuyển lương thực vũ khí bí mật.",
    lichSu: "Gắn liền với các hoạt động đưa đón bộ đội, du kích qua sông trong đêm, bến suối Túy Loan là một địa chỉ đỏ đầy tự hào của vùng quê Hòa Vang.",
    hinhAnh: "images/bensuoi.webp",
    googleMaps: "https://www.google.com/maps?q=15.996116958933936,108.14091191375506",
    video: "https://www.youtube.com/embed/SOfv6wA-Yco"
  }
];
